#!/usr/bin/env python3
from supabase_client import supabase
from datetime import datetime, timezone
import random

def main():
    alert = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "src_ip": "10.0.0.%d" % random.randint(2, 254),
        "dst_ip": "192.168.1.%d" % random.randint(2, 254),
        "protocol": "TCP",
        "threat_level": random.randint(1, 5),
        "threats": ["test-alert", "port-scan"],
        "packet_size": random.randint(60, 1500),
        "extra": {"note": "generated by send_test_alert.py"}
    }
    print("Inserting alert:", alert)
    supabase.table("alerts").insert(alert).execute()
    print("Done.")

if __name__ == "__main__":
    main()
