// Database type definitions for Supabase schema
export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          username: string;
          email: string;
          password_hash: string;
          full_name: string;
          role: 'security_admin' | 'security_manager' | 'security_analyst' | 'security_viewer';
          role_level: number;
          department: string | null;
          is_active: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          username: string;
          email: string;
          password_hash: string;
          full_name: string;
          role?: 'security_admin' | 'security_manager' | 'security_analyst' | 'security_viewer';
          role_level?: number;
          department?: string | null;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          username?: string;
          email?: string;
          password_hash?: string;
          full_name?: string;
          role?: 'security_admin' | 'security_manager' | 'security_analyst' | 'security_viewer';
          role_level?: number;
          department?: string | null;
          is_active?: boolean;
          last_login?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
      };
      incidents: {
        Row: {
          id: string;
          incident_number: string;
          title: string;
          description: string;
          incident_type: 'malware' | 'intrusion' | 'ddos' | 'phishing' | 'data_breach' | 'brute_force' | 'insider_threat' | 'ransomware';
          severity: 'low' | 'medium' | 'high' | 'critical';
          status: 'detected' | 'investigating' | 'contained' | 'resolved' | 'closed';
          source_ip: string | null;
          destination_ip: string | null;
          source_system: string | null;
          target_system: string | null;
          affected_systems: string[] | null;
          indicators_of_compromise: string[] | null;
          mitre_tactics: string[] | null;
          mitre_techniques: string[] | null;
          confidence_score: number | null;
          risk_score: number | null;
          assigned_to: string | null;
          reported_by: string | null;
          detected_at: string;
          first_seen: string | null;
          last_seen: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          incident_number?: string;
          title: string;
          description: string;
          incident_type: 'malware' | 'intrusion' | 'ddos' | 'phishing' | 'data_breach' | 'brute_force' | 'insider_threat' | 'ransomware';
          severity: 'low' | 'medium' | 'high' | 'critical';
          status?: 'detected' | 'investigating' | 'contained' | 'resolved' | 'closed';
          source_ip?: string | null;
          destination_ip?: string | null;
          source_system?: string | null;
          target_system?: string | null;
          affected_systems?: string[] | null;
          indicators_of_compromise?: string[] | null;
          mitre_tactics?: string[] | null;
          mitre_techniques?: string[] | null;
          confidence_score?: number | null;
          risk_score?: number | null;
          assigned_to?: string | null;
          reported_by?: string | null;
          detected_at?: string;
          first_seen?: string | null;
          last_seen?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          incident_number?: string;
          title?: string;
          description?: string;
          incident_type?: 'malware' | 'intrusion' | 'ddos' | 'phishing' | 'data_breach' | 'brute_force' | 'insider_threat' | 'ransomware';
          severity?: 'low' | 'medium' | 'high' | 'critical';
          status?: 'detected' | 'investigating' | 'contained' | 'resolved' | 'closed';
          source_ip?: string | null;
          destination_ip?: string | null;
          source_system?: string | null;
          target_system?: string | null;
          affected_systems?: string[] | null;
          indicators_of_compromise?: string[] | null;
          mitre_tactics?: string[] | null;
          mitre_techniques?: string[] | null;
          confidence_score?: number | null;
          risk_score?: number | null;
          assigned_to?: string | null;
          reported_by?: string | null;
          detected_at?: string;
          first_seen?: string | null;
          last_seen?: string | null;
          resolved_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      alerts: {
        Row: {
          id: string;
          alert_type: 'info' | 'warning' | 'error' | 'critical';
          title: string;
          message: string;
          source_system: string;
          source_ip: string | null;
          destination_ip: string | null;
          risk_score: number | null;
          confidence: number | null;
          is_acknowledged: boolean;
          acknowledged_by: string | null;
          acknowledged_at: string | null;
          is_duplicate: boolean;
          original_alert_id: string | null;
          correlation_id: string | null;
          related_incident_id: string | null;
          raw_data: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          alert_type: 'info' | 'warning' | 'error' | 'critical';
          title: string;
          message: string;
          source_system: string;
          source_ip?: string | null;
          destination_ip?: string | null;
          risk_score?: number | null;
          confidence?: number | null;
          is_acknowledged?: boolean;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          is_duplicate?: boolean;
          original_alert_id?: string | null;
          correlation_id?: string | null;
          related_incident_id?: string | null;
          raw_data?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          alert_type?: 'info' | 'warning' | 'error' | 'critical';
          title?: string;
          message?: string;
          source_system?: string;
          source_ip?: string | null;
          destination_ip?: string | null;
          risk_score?: number | null;
          confidence?: number | null;
          is_acknowledged?: boolean;
          acknowledged_by?: string | null;
          acknowledged_at?: string | null;
          is_duplicate?: boolean;
          original_alert_id?: string | null;
          correlation_id?: string | null;
          related_incident_id?: string | null;
          raw_data?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      network_traffic: {
        Row: {
          id: string;
          timestamp: string;
          source_ip: string;
          destination_ip: string;
          source_port: number | null;
          destination_port: number | null;
          protocol: string;
          packet_size: number | null;
          bytes_transferred: number | null;
          connection_duration: string | null;
          is_suspicious: boolean;
          threat_indicators: string[] | null;
          geolocation: any | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          timestamp?: string;
          source_ip: string;
          destination_ip: string;
          source_port?: number | null;
          destination_port?: number | null;
          protocol: string;
          packet_size?: number | null;
          bytes_transferred?: number | null;
          connection_duration?: string | null;
          is_suspicious?: boolean;
          threat_indicators?: string[] | null;
          geolocation?: any | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          timestamp?: string;
          source_ip?: string;
          destination_ip?: string;
          source_port?: number | null;
          destination_port?: number | null;
          protocol?: string;
          packet_size?: number | null;
          bytes_transferred?: number | null;
          connection_duration?: string | null;
          is_suspicious?: boolean;
          threat_indicators?: string[] | null;
          geolocation?: any | null;
          created_at?: string;
        };
      };
      system_status: {
        Row: {
          id: string;
          component_name: string;
          component_type: 'firewall' | 'ids_ips' | 'antivirus' | 'waf' | 'siem' | 'endpoint' | 'network' | 'database';
          status: 'online' | 'offline' | 'warning' | 'error' | 'maintenance';
          health_score: number | null;
          response_time_ms: number | null;
          cpu_usage: number | null;
          memory_usage: number | null;
          disk_usage: number | null;
          last_check: string;
          error_message: string | null;
          metadata: any | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          component_name: string;
          component_type: 'firewall' | 'ids_ips' | 'antivirus' | 'waf' | 'siem' | 'endpoint' | 'network' | 'database';
          status: 'online' | 'offline' | 'warning' | 'error' | 'maintenance';
          health_score?: number | null;
          response_time_ms?: number | null;
          cpu_usage?: number | null;
          memory_usage?: number | null;
          disk_usage?: number | null;
          last_check?: string;
          error_message?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          component_name?: string;
          component_type?: 'firewall' | 'ids_ips' | 'antivirus' | 'waf' | 'siem' | 'endpoint' | 'network' | 'database';
          status?: 'online' | 'offline' | 'warning' | 'error' | 'maintenance';
          health_score?: number | null;
          response_time_ms?: number | null;
          cpu_usage?: number | null;
          memory_usage?: number | null;
          disk_usage?: number | null;
          last_check?: string;
          error_message?: string | null;
          metadata?: any | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      email_configurations: {
        Row: {
          id: string;
          name: string;
          smtp_server: string;
          smtp_port: number;
          smtp_username: string;
          smtp_password_encrypted: string;
          use_tls: boolean;
          from_email: string;
          to_emails: string[];
          subject_prefix: string;
          cpu_threshold: number;
          memory_threshold: number;
          disk_threshold: number;
          failed_login_threshold: number;
          network_scan_threshold: number;
          check_interval: number;
          cooldown_period: number;
          enable_threat_detection: boolean;
          send_threat_emails: boolean;
          critical_incidents_only: boolean;
          is_active: boolean;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          smtp_server: string;
          smtp_port?: number;
          smtp_username: string;
          smtp_password_encrypted: string;
          use_tls?: boolean;
          from_email: string;
          to_emails: string[];
          subject_prefix?: string;
          cpu_threshold?: number;
          memory_threshold?: number;
          disk_threshold?: number;
          failed_login_threshold?: number;
          network_scan_threshold?: number;
          check_interval?: number;
          cooldown_period?: number;
          enable_threat_detection?: boolean;
          send_threat_emails?: boolean;
          critical_incidents_only?: boolean;
          is_active?: boolean;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          smtp_server?: string;
          smtp_port?: number;
          smtp_username?: string;
          smtp_password_encrypted?: string;
          use_tls?: boolean;
          from_email?: string;
          to_emails?: string[];
          subject_prefix?: string;
          cpu_threshold?: number;
          memory_threshold?: number;
          disk_threshold?: number;
          failed_login_threshold?: number;
          network_scan_threshold?: number;
          check_interval?: number;
          cooldown_period?: number;
          enable_threat_detection?: boolean;
          send_threat_emails?: boolean;
          critical_incidents_only?: boolean;
          is_active?: boolean;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      threat_intelligence: {
        Row: {
          id: string;
          indicator_type: 'ip' | 'domain' | 'url' | 'hash' | 'email' | 'file_path';
          indicator_value: string;
          threat_type: string;
          confidence: number | null;
          severity: 'low' | 'medium' | 'high' | 'critical' | null;
          source: string;
          description: string | null;
          first_seen: string;
          last_seen: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          indicator_type: 'ip' | 'domain' | 'url' | 'hash' | 'email' | 'file_path';
          indicator_value: string;
          threat_type: string;
          confidence?: number | null;
          severity?: 'low' | 'medium' | 'high' | 'critical' | null;
          source: string;
          description?: string | null;
          first_seen?: string;
          last_seen?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          indicator_type?: 'ip' | 'domain' | 'url' | 'hash' | 'email' | 'file_path';
          indicator_value?: string;
          threat_type?: string;
          confidence?: number | null;
          severity?: 'low' | 'medium' | 'high' | 'critical' | null;
          source?: string;
          description?: string | null;
          first_seen?: string;
          last_seen?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: string;
          table_name: string;
          record_id: string;
          action: 'INSERT' | 'UPDATE' | 'DELETE';
          old_values: any | null;
          new_values: any | null;
          changed_by: string | null;
          ip_address: string | null;
          user_agent: string | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          table_name: string;
          record_id: string;
          action: 'INSERT' | 'UPDATE' | 'DELETE';
          old_values?: any | null;
          new_values?: any | null;
          changed_by?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          timestamp?: string;
        };
        Update: {
          id?: string;
          table_name?: string;
          record_id?: string;
          action?: 'INSERT' | 'UPDATE' | 'DELETE';
          old_values?: any | null;
          new_values?: any | null;
          changed_by?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          timestamp?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}